# Generated by Django 6.0.5 on 2026-05-22 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintraining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='source',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='source', to='admintraining.source'),
            preserve_default=False,
        ),
    ]
