# Generated by Django 6.0.5 on 2026-05-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admintraining', '0002_certificate_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='training',
        ),
    ]
