# Generated by Django 6.0.5 on 2026-05-22 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintraining', '0003_rename_title_training_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='source',
        ),
        migrations.AddField(
            model_name='certificate',
            name='training',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='admintraining.training'),
            preserve_default=False,
        ),
    ]
