# Generated by Django 6.0.5 on 2026-05-25 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admintraining', '0004_rename_name_training_title_remove_certificate_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training', to='admintraining.training'),
        ),
    ]
