# Generated by Django 6.0.5 on 2026-06-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_rename_caption_post_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='caption',
        ),
    ]
