# Generated by Django 6.0.5 on 2026-07-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, default=1, max_length=999999),
            preserve_default=False,
        ),
    ]
