# Generated by Django 6.0.5 on 2026-06-18 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github_token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
