# Generated by Django 6.0.5 on 2026-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_trajectory_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrepository',
            name='repo_url',
            field=models.URLField(),
        ),
    ]
