# Generated by Django 6.0.5 on 2026-05-19 14:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminprofile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='githubrepository',
            name='created_at',
        ),
        migrations.AddField(
            model_name='githubrepository',
            name='pushed_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
